[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

[dev]
  command = "npm run start"
  port = 8080
  publish = "_site" 