[build]
  publish = "_site"
  command = "node scripts/build-netlify.js"

[build.environment]
  NODE_VERSION = "16"
  NETLIFY = "true"

# Redirect any 404s to index for SPA-like behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Add headers to ensure CSS is properly loaded
[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "text/css"

[dev]
  command = "npm run start"
  port = 8080
  publish = "_site" 